### ISSUE TITLE
Google Account Banned?

### ISSUE THREAD

**Issue by cibersheep** [ubports/account-plugins#32]
I have changed the password of my google account and when calendar showed me the possibility to update the configuration, sync monitor opened to show me an error page of Accounts saying: «Account information was not able to be loaded».

1. Delete the account
2. Add new Google account and enter credentials

I got error message: Google Login temporary disabled for this app. Google didn't verify yet this apps to be able to be used with Google loging.

- I have tried with 2FA and with Less Secure Access turned on, both with the same result

**Comment by UniversalSuperBox** [comment]
This was fixed by using a new set of credentials for Google signins in https://github.com/ubports/account-plugins/pull/33. For that reason, I will close this report.

However, https://github.com/ubports/account-plugins/issues/40 is still an issue and is making it impossible for most people to sign in to a Google account on Ubuntu Touch.
