### ISSUE TITLE
Google: Unable to sign in Again

### ISSUE THREAD

**Issue by rubencarneiro** [ubports/account-plugins#40]
Guess this user agent string is also blocked.

**Comment by mardy** [comment]
Please provide some information. What account are you trying to create? can you provide a screenshot for the error?

**Comment by rubencarneiro** [comment]
> Please provide some information. What account are you trying to create? can you provide a screenshot for the error?

Google account sign in, user agent string as been blocked.

**Comment by mardy** [comment]
I just tried, and indeed it doesn't work for me either. If Google doesn't want us to use their services, I think we should just remove the account, unless someone can come up with a user-agent string that works (or any other solution, for that matter).

I'll still spend some time to investigate the issue, to make sure that the problem is indeed with the user-agent and not with some other protocol changes. But if nothing works, we should just remove it.

**Comment by mardy** [comment]
OK, I did some investigation. First I tried removing most of the OAuth scopes from `/usr/share/accounts/providers/google.provider`, to see if the error could be due to some permission; it didn't help.

Then I ran

    OAU_LOGGING_LEVEL=2 OAU_DAEMON_TIMEOUT=9999 online-accounts-service

to collect the logs while I was trying to create the account, and when the URL for the login page was printed, I tried to open it in the Morph browser instead. Surprise surprise, it worked.

It looks like Google is actively trying to prevent the user from authenticating within webviews:
https://security.googleblog.com/2019/04/better-protection-against-man-in-middle.html
https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html
https://support.google.com/accounts/answer/7675428?co=GENIE.Platform%3DAndroid&hl=en

All this suggests me that there must be some code within the chrome engine, that is capable of detecting whether the webview is part of a browser or embedded in some application.

It would be nice if someone with more experience with Morph (@mariogrip?) could help me understand whether there's something I need to implement in the Online Accounts webview to make the chromium engine think that we are a full-fledged browser.

Maybe Google is trying to open some frame? I see this in the logs:
```
Invalid 'X-Frame-Options' header encountered when loading 'https://accounts.youtube.com/accounts/CheckConnection?pmpo=https%3A%2F%2Faccounts.google.com&v=-913843931&timestamp=1586880261321': 'ALLOW-FROM https://accounts.google.com' is not a recognized directive. The header will be ignored.
```
The fact that the page is called `CheckConnection` makes me especially suspicious.

**Comment by rubencarneiro** [comment]
Remove the account, is not viable, people sync with google contacts.
Cant we implement this istead UA Strings.
https://wicg.github.io/ua-client-hints/

**Comment by rubencarneiro** [comment]
Fixed for now https://github.com/ubports/account-plugins/pull/43

**Comment by Flohack74** [comment]
> 
> 
> Remove the account, is not viable, people sync with google contacts.
> Cant we implement this istead UA Strings.
> https://wicg.github.io/ua-client-hints/

How should implementing this draft solve a problem where Google bans embedded browser frameworks? Thats not causing any improvement.

**Comment by GI9VANNI** [comment]
I updated my Nexus 5 to OTA-12 but unfortunately it's no longer possible to connect the Google account to synchronize the contacts. Morph Browser is not supported. How can I get around this?

**Comment by rubencarneiro** [comment]
try to install this then reboot https://github.com/rubencarneiro/account-plugins/releases

**Comment by GI9VANNI** [comment]
@rubencarneiro Hi, thanks for the answer!
Unfortunately I can't install the .deb file. I tried with:
`sudo dpkg -i account-plugin-google_0.15.0ubports1local.1586944513_all.deb`
but this error has returned:
`Read-only file system`
Which command should I use to install your fix?

**Comment by rubencarneiro** [comment]
> @rubencarneiro Hi, thanks for the answer!
> Unfortunately I can't install the .deb file. I tried with:
> `sudo dpkg -i account-plugin-google_0.15.0ubports1local.1586944513_all.deb`
> but this error has returned:
> `Read-only file system`
> Which command should I use to install your fix?

First do sudo -s
sudo mount -o remount,rw /
sudo dpkg -i "deb file"

**Comment by GI9VANNI** [comment]
It worked!
Now Google thinks my Nexus 5 is a Nexus 4, but it did give me access.
Thanks @rubencarneiro 👍

**Comment by stanwood77** [comment]
Thank you for this great workaround solution! Will this plugin be implemented by default in a future OTA?

**Comment by rubencarneiro** [comment]
> Thank you for this great workaround solution! Will this plugin be implemented by default in a future OTA?

Thats up to the Ubports team.

**Comment by ScardracS-zz** [comment]
I did some investigations too and found actually the chromium version of morph is v65, which is too old for Google (in fact Google is actively blocking it for access to Google accounts and so on). A solution could be to try to update chromium to latest version (at least v80)

**Comment by Flohack74** [comment]
We explained already in detail why this is no fix that will work for all users (Google seems to be pretty inconsistent about it, but I think they will close all remaining gaps soon): Morph browser uses QtWebEngine which in turn uses a Chromium browser process. And that again is started by the accounts plugin to verify the details. Now see this snippet:
![grafik](https://user-images.githubusercontent.com/16186470/87395618-f21b9a80-c5b1-11ea-8361-e1ce1e0b791d.png)
Taken from https://support.google.com/accounts/answer/7675428?co=GENIE.Platform%3DDesktop&hl=en
What it basically say is: The browser cannot be secure if its embedded into another process, since that process could be a man-in-the-middle and could steal identity data during the handshake.
So I expect this User Agent workaround to stop sooner or later again. See that they wrote it "might stop login" so it sometimes works, sometimes does not. We do not want to a) make fixes that work only for a few users b) fix this thing again and again. We need a permanent solution for this, and as long as nobody comes up with a real implementation that works for all users in all cases its not an accepted solution. Maybe @mardy can give some more insights about the problem here.

**Comment by Flohack74** [comment]
@ScardracS we do not have control over the Chromium version, as we use the one that comes with Qt version that is installed. We will upgrade soon to Qt 5.15 that will bump the version of CHromium probably, but the problem has nothing to do with the version. Its because Google can detect that the browser process is hosted by another app, and thats thought to have potential security risks. Read more here: https://9to5google.com/2019/04/18/google-block-man-in-the-middle/

**Comment by ScardracS-zz** [comment]
Thanks @Flohack74 for the clarifications :)

**Comment by mardy** [comment]
Hi everybody,
  I would like to ask people who are affected by this bug to try out the following steps:

1. From a terminal in the device (or in a SSH session), run the following commands (just copy/paste them):
```
# Remount the filesystem to read-write mode:
sudo mount -o remount,rw /

# Update the Google account configuration
sudo sh -c "cat > /usr/share/accounts/providers/google.provider" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<provider id="google">
  <name>Google</name>
  <description>Includes Gmail, Google Docs, Google+, YouTube and Picasa</description>
  <icon>google</icon>
  <translations>account-plugins</translations>
  <domains>.*google\.com</domains>

  <template>
    <group name="auth">
      <setting name="method">oauth2</setting>
      <setting name="mechanism">web_server</setting>
      <group name="oauth2">
        <group name="web_server">
          <setting name="Host">accounts.google.com</setting>
          
          <setting name="AuthPath">o/oauth2/auth?access_type=offline</setting>
          <setting name="TokenPath">o/oauth2/token</setting>
          <setting name="RedirectUri">http://localhost:6392/oauth_callback</setting>
          <setting name="ResponseType">code</setting>
          <setting type="as" name="Scope">['email','profile','https://www.google.com/m8/feeds/','https://www.googleapis.com/auth/calendar','https://www.googleapis.com/auth/carddav']</setting>
          <setting name="ClientId">1032863574955-44edra7uap3789kuc3cmplofd620ombh.apps.googleusercontent.com</setting>
          <setting name="ClientSecret">QvEYYpxvrn6Oo-mOWZ_obhre</setting>
          <setting type="as" name="AllowedSchemes">['https','http']</setting>
          <setting type="b" name="ForceClientAuthViaRequestBody">true</setting>
        </group>
      </group>
    </group>
  </template>
</provider>
EOF
```

2. Try creating a Google account again.

If it works, please add a thumbs up :-) If it doesn't, please describe the error you encounter in as much detail as possible.

**Comment by Flohack74** [comment]
@mardy did we forget this for the release notes of OTA-113? Its also not marked to be on the OTA-13 board.

**Comment by Flohack74** [comment]
Because somebody told me it works in OTA-13, but was that the fix with the user-agent which works sometimes probably. Should we target it for OTA-14 then ?

**Comment by mardy** [comment]
The MR #44, which contains the fix suggested here, was merged only after OTA-13 was released. So the fix will be only in OTA-14.

**Comment by Flohack74** [comment]
Thats strange. But OK ;) thx

**Comment by zubozrout** [comment]
Hi,
I've relatively recently reinstalled my MX4 and was unable to log in to Google to sync contacts and calendars ever since. I've even tried this a while ago https://github.com/ubports/account-plugins/issues/40#issuecomment-686608782 but with no luck at that time. Since then I've also reinstalled my phone completely through ubuntu-device-flash (without clearing the userspace, but trying to get rid of my manual modifications to the rootfs).

I guess this fix is already in devel but unfortunately it makes no difference for me.

Here is the message I was getting:
![obrazek](https://user-images.githubusercontent.com/3088349/94785599-2abc5a80-03d0-11eb-8faf-853f4a4ee6a3.png)
saying this in English: https://support.google.com/accounts/thread/22873505

However, when I installed this: https://github.com/ubports/account-plugins/issues/40#issuecomment-629549091
as recommended to me by @lduboeuf it started working.

So I guess maybe this fix is not sufficient and user agent string also needs to change(?)

**Comment by rubencarneiro** [comment]
> Hi,
> I've relatively recently reinstalled my MX4 and was unable to log in to Google to sync contacts and calendars ever since. I've even tried this a while ago [#40 (comment)](https://github.com/ubports/account-plugins/issues/40#issuecomment-686608782) but with no luck at that time. Since then I've also reinstalled my phone completely through ubuntu-device-flash (without clearing the userspace, but trying to get rid of my manual modifications to the rootfs).
> 
> I guess this fix is already in devel but unfortunately it makes no difference for me.
> 
> Here is the message I was getting:
> ![obrazek](https://user-images.githubusercontent.com/3088349/94785599-2abc5a80-03d0-11eb-8faf-853f4a4ee6a3.png)
> saying this in English: https://support.google.com/accounts/thread/22873505
> 
> However, when I installed this: [#40 (comment)](https://github.com/ubports/account-plugins/issues/40#issuecomment-629549091)
> as recommended to me by @lduboeuf it started working.
> 
> So I guess maybe this fix is not sufficient and user agent string also needs to change(?)

reinstall and reboot the device or wait for Alfred fix.

**Comment by zubozrout** [comment]
Hi @rubencarneiro, I did that using your accounts-plugin package and it worked as noted. What I was more concerned about with my post here is that the sole fix from @mardy was not enough for me and perhaps a combination of both should be merged?

**Comment by UniversalSuperBox** [comment]
Unfortunately, it appears that the fix did not actually solve the problem for many users, myself included.

![screenshot20201023_095023070](https://user-images.githubusercontent.com/21966173/97019502-03ac0100-1516-11eb-8e0e-4c2313b6e4b9.png)

This screenshot was taken on the devel image for 2020-10-23. This is shown immediately after entering your email address.

**Comment by UniversalSuperBox** [comment]
Oh, the account-plugins build failed. That's why. Unfortunately this won't be part of this release thanks to freeze, but I'll kick the build after OTA-14 is released.

**Comment by rubencarneiro** [comment]
> Oh, the account-plugins build failed. That's why. Unfortunately this won't be part of this release thanks to freeze, but I'll kick the build after OTA-14 is released.

And if you install the deb, does it works?

**Comment by stanwood77** [comment]
I confirm, deb plugin works (tested on N5, OTA 13 stable). 
I did reinstall UT on my N5 using UBports installer and tried to login to Google: Authentication denied. Than I reinstall the deb file and logged successfully into my Google account. Calendar and contacts are well synchronized

**Comment by ghost** [comment]
Hi Everyone,

I am very, very new to Ubuntu Touch.  So, I'm am sorry for the silly question.  However, how do I install a deb file on this machine?

**Comment by rubencarneiro** [comment]
> Hi Everyone,
> 
> I am very, very new to Ubuntu Touch. So, I'm am sorry for the silly question. However, how do I install a deb file on this machine?

Donwload, copy to your device Downloads folder then open a terminal on the device and do the following commands:
sudo mount -o remount,rw /
cd Downloads
sudo dpkg -i *.deb
after that reboot

**Comment by ghost** [comment]
It looked like a permission issue.  Thanks!

**Comment by peat-psuwit** [comment]
I triggered the rebuild and it seems to build now. Please wait until the next devel image update and then please see if the issue is solved.

**Comment by UniversalSuperBox** [comment]
It is not fixed, I still receive "Couldn't sign you in: This browser or app may not be secure..."

**Comment by stanwood77** [comment]
Did you allow the access to "less secured applications" in your Google account?

**Comment by UniversalSuperBox** [comment]
Toggling this feature does not seem to change anything for OAUTH access. Indeed, Google states that it is meant for "Apple's Mail app, Mozilla Thunderbird, or Microsoft Outlook" on this page: https://support.google.com/accounts/answer/6009563

**Comment by stanwood77** [comment]
Regarding the .deb plugging: 
I regret to inform you that the Google Calendar synchronization works only when you first activate your Google Account in the settings; but does not synchronize anymore afterwards.  No error message, just nothing happens when I add a new event in Google or in UT calendar.
I tried to manually refresh the data in calendar, deactivate/reactivate the calendar sync in settings, uncheck / check my google calendar account in the calendar settings,.....Unsuccessfully. 
No problem with Google contacts.
I have each time to delete the Google account and then recreate it to synchronize the calendar data again.
Tested on 2 devices: Nexus 5 OTA-15 Stable + Vollaphone OTA-15 Stable
Hope this feedback will help.
Regards, Steve

**Comment by rubencarneiro** [comment]
> Regarding the .deb plugging:
> I regret to inform you that the Google Calendar synchronization works only when you first activate your Google Account in the settings; but does not synchronize anymore afterwards. No error message, just nothing happens when I add a new event in Google or in UT calendar.
> I tried to manually refresh the data in calendar, deactivate/reactivate the calendar sync in settings, uncheck / check my google calendar account in the calendar settings,.....Unsuccessfully.
> No problem with Google contacts.
> I have each time to delete the Google account and then recreate it to synchronize the calendar data again.
> Tested on 2 devices: Nexus 5 OTA-15 Stable + Vollaphone OTA-15 Stable
> Hope this feedback will help.
> Regards, Steve

You need to authorize third party applications on your google account.

**Comment by ginggs** [comment]
@stanwood77 this issue is still marked Open, so surely not expected to be fixed in OTA-15.

**Comment by UniversalSuperBox** [comment]
It is interesting that the behavior has changed for the worse, though. Thank you for your report.

**Comment by stanwood77** [comment]
> You need to authorize third party applications on your google account.

Third party access is well authorized in main Google account settings. 
Sync does indeed work immediately at the initial Google account set-up in Ubuntu Touch settings => Online accounts.
Than, no more automatic sync between Google and UT calendar (but works 100% with Google Contacts).

**Comment by rubencarneiro** [comment]
> Regarding the .deb plugging:
> I regret to inform you that the Google Calendar synchronization works only when you first activate your Google Account in the settings; but does not synchronize anymore afterwards. No error message, just nothing happens when I add a new event in Google or in UT calendar.
> I tried to manually refresh the data in calendar, deactivate/reactivate the calendar sync in settings, uncheck / check my google calendar account in the calendar settings,.....Unsuccessfully.
> No problem with Google contacts.
> I have each time to delete the Google account and then recreate it to synchronize the calendar data again.
> Tested on 2 devices: Nexus 5 OTA-15 Stable + Vollaphone OTA-15 Stable
> Hope this feedback will help.
> Regards, Steve

ok so i created a new event on ubuntu desktop calendar and it was automaticly synk on ubuntu touch calendar, the problem seems to the inverse if you create on ubuntu touch it will not push the event to google account.

**Comment by Fuseteam** [comment]
it might be interesting that logging in still works in online accounts plugin from the unity 7 desktop enviroment on ubuntu 18.04
maybe we could find a hint to fix this permenantly

**Comment by Fuseteam** [comment]
> 
> ```
> Invalid 'X-Frame-Options' header encountered when loading 'https://accounts.youtube.com/accounts/CheckConnection?pmpo=https%3A%2F%2Faccounts.google.com&v=-913843931&timestamp=1586880261321': 'ALLOW-FROM https://accounts.google.com' is not a recognized directive. The header will be ignored.
> ```
> 
> The fact that the page is called `CheckConnection` makes me especially suspicious.

appearently its a webstandard that differentiates between the two: https://support.mozilla.org/en-US/kb/xframe-neterror-page?as=u&utm_source=inproduct

**Comment by mardy** [comment]
I have a couple of merge requests implementing a different solution, which is the one recommended by Google. This does not rely on any specific user-agent string, but has the cost of worsening the user experience: the user will have to login in the Morph browser, then manually switch back to the application (or System Settings, if the account creation started from there). But this is what Google mandates. :-(

**Testers are welcome**: please install the `ubuntu-system-settings-online-accounts` deb package from [here](https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fubuntu-system-settings-online-accounts/detail/PR-16/1/artifacts) and the `account-plugin-google` from [here](https://ci.ubports.com/blue/organizations/jenkins/ubports%2Faccount-plugins/detail/PR-45/1/artifacts). Please let me know how it works.

**Comment by Fuseteam** [comment]
@mardy could morph be opened via url dispatcher maybe? tho I guess the way back would be an open question

**Comment by mardy** [comment]
> @mardy could morph be opened via url dispatcher maybe? tho I guess the way back would be an open question

Morph opens fine already via url-dispatcher, the problem is on the way back.

**Comment by Fuseteam** [comment]
> > @mardy could morph be opened via url dispatcher maybe? tho I guess the way back would be an open question
> 
> Morph opens fine already via url-dispatcher, the problem is on the way back.

ah sorry misread

**Comment by lduboeuf** [comment]
Tested on my side on N5, so the sync is fine, only thing is that we don't know in the app ( e.g contacts) if its ok. I don't remember if we should see something under "Add google account "

**Comment by mardy** [comment]
> Tested on my side on N5, so the sync is fine, only thing is that we don't know in the app ( e.g contacts) if its ok. I don't remember if we should see something under "Add google account "

That has not been changed, unfrotunately a clear feedback has always been missing :-)

**Comment by nanu-c** [comment]
i have the same on Axolotl, i need to solve a recaptcha on a specific page. Why not load a webengineview and catch the result?

**Comment by mardy** [comment]
> i have the same on Axolotl, i need to solve a recaptcha on a specific page. Why not load a webengineview and catch the result?

Can you please explain better what is happening? Are you able to solve the captcha and continue, or what exactly is the problem?

**Comment by ShadowEO** [comment]
So changing the user-agent to Microsoft Edge's agent and restarting Unity 8, then attempting to add the Google account succeeds. It seems Google is blocking the Morph user-agent completely and some older Chromium user-agents as I had to find a recent one.

**Comment by Fuseteam** [comment]
i took a look how google redirects back to a site from another window on desktop i noticed it makes use of a `redirect_uri` to bring the user back to the original site, could be use that to send the user back to the settings? 
here's a few (url decoded) examples i tested:
```
https://accounts.google.com/o/oauth2/v2/auth/oauthchooseaccount?client_id=72103009834-ccrvro0kt03tpd7vrsi0c7e3gqjmsl4a.apps.googleusercontent.com&redirect_uri=https://create.kahoot.it/auth/google/popup&response_type=id_token&scope=openid email profile&state=c28dc12d332349a09728765daa63d46e&nonce=b454624daa874277a665b9a504ad4482&prompt=select_account&display=popup&flowName=GeneralOAuthFlow
https://accounts.google.com/o/oauth2/auth/oauthchooseaccount?response_type=permission id_token code&scope=profile email&openid.realm&include_granted_scopes=true&redirect_uri=storagerelay://https/www.udemy.com?id=auth186180&client_id=700206021005-as1l679sch207mp70msgjhma1krf3k9q.apps.googleusercontent.com&ss_domain=https://www.udemy.com&gsiwebsdk=shim&access_type=offline&flowName=GeneralOAuthFlow
```
in all the cases i tested `redirect_uri` and `ss_domain` seems to be the part that truly differs

**Comment by zubozrout** [comment]
> **Testers are welcome**: please install the `ubuntu-system-settings-online-accounts` deb package ... and the `account-plugin-google`.

I finally gave it a try since missing calendar/contacts sync is quite painful and this is awesome, it works very well on MX4, thank you :). Hopefully this gets merged soon-ish to make the process easier. And since signing in a web browser has to be done separately this is especially convenient that I didn't actually have to enter my credentials all over again if already filled in a web browser.

**Comment by ivoxavier** [comment]
It's working now.

Tested on FP2: devel channel image (2021-11-23/2)

**Comment by ivoxavier** [comment]
Hi, it's been working correctly since 17 days ago for me.

Tested scenarios:
. phone reflashed  setting up the google account.
. removed the google account then re-added it again, everything sycned.
. added the google account by the icon on contacts app worked
. add the google account by system-settings App

Since this https://github.com/ubports/ubuntu-system-settings-online-accounts/issues/18 is related to his issue. Both are done.


Test info:
device: FP2
channel: devel (2021-12-06)

**Comment by Fuseteam** [comment]
i can confirm i can log into google via system settings now
